version: "3.8"

services:
  mongo_api:
    build:
      context: ./mongo_api
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    networks:
      - backend-network

  notifications_api:
    build:
      context: ./notifications_api
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - backend-network

  storage_api:
    build:
      context: ./storage_api
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    networks:
      - backend-network

  chroma_api:
    build:
      context: ./chroma_api
      dockerfile: Dockerfile
    ports:
      - "2525:2525"
    networks:
      - backend-network
    depends_on:
      - redis

  langchain_api:
    build:
      context: ./langchain_api
      dockerfile: Dockerfile
    ports:
      - "2020:2020"
    networks:
      - backend-network
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend-network

networks:
  backend-network:
